### ISSUE TITLE
which theano version should be?

### ISSUE THREAD

**Issue by SeekPoint** [yyaghoobzadeh/figment#1]

**Comment by SeekPoint** [comment]
figure it out, 0.8.2 works

would you plan build a tensorflow version?

**Comment by yyaghoobzadeh** [comment]
Ok, great! 
Unfortunately, I don't have plans to build a Tensorflow version, but it should be very straightforward to do so since the network architecture is very simple. 
You just need to build the data properly (which you can use the same code for that) and make the tensors. Then it's basically an MLP + binary cross entropy.
